[metadata]
name = html_image_base64
version = 1.0.0
description = Convierte imagenes referenciadas en archivos HTML a Base64 embebido (data URI)
long_description = file: README.md
long_description_content_type = text/markdown

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.9

[options.packages.find]
where = src
